- opensuse-tomcat-jre17-juli-image/src/main/docker/Dockerfile
- pom.xml
- release-notes-1.1.0.md
Ticket: https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=632168
> D632168: Upgraded tomcat to 9.0.73

- release-notes-1.4.0.md
Ticket: https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=778002
> US778002: Release preparation

- opensuse-tomcat-jre17-juli-image/src/main/docker/Dockerfile
- pom.xml
- release-notes-1.5.0.md
Ticket: https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=788018
> US788018: Updated to Tomcat 9.0.76

- release-notes-1.5.0.md
Ticket: https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=795027
> US795027: Release preparation

- release-notes-1.6.0.md
Ticket: https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=846018
> US846018: Release preparation

- release-notes-2.0.0.md
Ticket: https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=863005
> US863005: Release prep

- release-notes-1.7.0.md
Ticket: https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=866069
> US866069: Release preparation

- caf-logging-tomcat-juli/pom.xml
- opensuse-tomcat-jre17-image/pom.xml
- opensuse-tomcat-jre17-image/src/main/docker/Dockerfile
- opensuse-tomcat-jre17-image/src/main/docker/logback-access.xml
- opensuse-tomcat-jre17-image/src/main/docker/logback.xml
- opensuse-tomcat-jre17-image/src/main/docker/server.xslt
- opensuse-tomcat-jre17-image/src/main/docker/setenv.bat
- opensuse-tomcat-jre17-image/src/main/docker/setenv.sh
- opensuse-tomcat-jre17-image/src/test/resources/test.html
- opensuse-tomcat-jre17-juli-image/pom.xml
- opensuse-tomcat-jre17-juli-image/src/main/docker/Dockerfile
- opensuse-tomcat-jre17-juli-image/src/main/docker/logging.properties
- opensuse-tomcat-jre17-juli-image/src/main/docker/server.xslt
- opensuse-tomcat-jre17-juli-image/src/main/docker/startup.d/setup-loglevel.sh
- opensuse-tomcat-jre17-juli-image/src/main/docker/startup.d/setup-tomcat-ssl-cert.sh
- opensuse-tomcat-jre17-juli-image/src/test/resources/test.html
- pom.xml
Ticket: https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=868108
> US868108: Update Copyright statements to 2024

- release-notes-1.7.1.md
Ticket: https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=871037
> US871037: Release preparation

- opensuse-tomcat-jre17-juli-image/src/main/docker/Dockerfile
Ticket: https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=887056
> US887056: Download tomcat package during build

- README.md
- opensuse-tomcat-jre17-image/src/main/docker/Dockerfile
- opensuse-tomcat-jre17-juli-image/src/main/docker/Dockerfile
- release-notes-2.1.0.md
https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=889116
> US889116: Replace gosu with su-exec

- opensuse-tomcat-jre17-image/src/main/docker/Dockerfile
- opensuse-tomcat-jre17-juli-image/src/main/docker/Dockerfile
- release-notes-2.1.0.md
Ticket: https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=890036
> US890036: Release preparation

- pom.xml
Ticket: https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=915081
> I915081: Resolve tomcat component version mismatch

- opensuse-tomcat-jre17-image/src/main/docker/Dockerfile
- opensuse-tomcat-jre17-juli-image/pom.xml
- opensuse-tomcat-jre17-juli-image/src/main/docker/Dockerfile
- pom.xml
https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=888096
> US888096: Use docker image version management plugin

- opensuse-tomcat-jre17-juli-image/src/main/docker/Dockerfile
- pom.xml
- release-notes-2.3.0.md
Ticket: https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=921216
Logback also updated to 1.5.6
> US921216: Tomcat updated to 10.1.24

- pom.xml
- release-notes-2.4.0.md
Ticket: https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=920085
> US920085: Release preparation

- pom.xml
- release-notes-2.5.0.md
Ticket: https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=977107
> US977107: Release preparation

- opensuse-tomcat-jre17-juli-image/src/main/docker/Dockerfile
- pom.xml
- release-notes-2.6.0.md
Ticket: https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=1000036
> US1000036: Release preparation

- pom.xml
- release-notes-2.6.3.md
Ticket: https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=1019001
> US1019001: Release preparation

- pom.xml
- release-notes-2.8.1.md
Ticket: https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=1041232
> US1041232: Release preparation
